"""ad  phone

Revision ID: 0e4e5785d15d
Revises: fc7a67c09dab
Create Date: 2024-01-26 23:29:55.179300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4e5785d15d'
down_revision: Union[str, None] = 'fc7a67c09dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'phone')
    # ### end Alembic commands ###
