"""ad foreignkey to resume

Revision ID: 26ceba05f6b2
Revises: 1c0b641e36d0
Create Date: 2024-01-26 23:59:59.134991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ceba05f6b2'
down_revision: Union[str, None] = '1c0b641e36d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'resume', 'users', ['user_id'], ['id'])
    op.drop_column('resume', 'user_id_temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('user_id_temp', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'resume', 'users', ['user_id_temp'], ['id'])
    op.drop_constraint(None, 'resume', type_='foreignkey')
    # ### end Alembic commands for SQLite copy-and-move strategy ###

