"""delete phone

Revision ID: 92d75e4f792f
Revises: 0b58894ff3a2
Create Date: 2024-01-27 00:24:53.105515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d75e4f792f'
down_revision: Union[str, None] = '0b58894ff3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('phone', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
