"""delete phone

Revision ID: fc7a67c09dab
Revises: da9d22ad7437
Create Date: 2024-01-26 23:29:30.966502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7a67c09dab'
down_revision: Union[str, None] = 'da9d22ad7437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('phone', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
